### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by tnicolaisen-snabble**
Of course the day *after* I release all the otel things are released :D

### CODE REVIEW

**Comment by tnicolaisen-snabble** [comment]
Seeing this again:

> --- FAIL: Test_NewGlobalNoopTraceProvider_SetsTheGlobalProvider (0.00s)
panic: cannot merge resource due to conflicting Schema URL [recovered]

https://github.com/open-telemetry/opentelemetry-go/issues/2341 is closed (not sure how it was resolved since the problem still occurs for us). There's a pointer to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5036 which is still open.

**Comment by J-Rocke** [comment]
Zumindest haben wir jetzt eine zentrale Stelle wo wir das lösen können

**Comment by tnicolaisen-snabble** [comment]
We just have to manually upgrade to the corresponding schema each time :heavy_check_mark:

**Comment by tnicolaisen-snabble** [comment]
There's also a schema-less function we could use that would probably avoid this hassle, but then we won't get reminded to upgrade the schema. That could lead to issues way down the road, when tooling expects us to follow a certain schema, I suppose.

**Pull request merged**
